swagger: "2.0"
info: {}
basePath: /api
paths:
  /v1/:
    get:
      tags:
      - v1
      description: get Biz
      operationId: BizController.GetAll
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Biz'
        "403":
          description: ""
    post:
      tags:
      - v1
      description: create Biz
      operationId: BizController.Create
      parameters:
      - in: body
        name: body
        description: body for Biz content
        required: true
        schema:
          $ref: '#/definitions/models.Biz'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Biz'
        "403":
          description: body is empty
  /v1/{id}:
    get:
      tags:
      - v1
      description: get Biz by id
      operationId: BizController.GetOne
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Biz'
        "403":
          description: :id is empty
    put:
      tags:
      - v1
      description: update the Biz
      operationId: BizController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Biz content
        required: true
        schema:
          $ref: '#/definitions/models.Biz'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Biz'
        "403":
          description: :id is not int
    delete:
      tags:
      - v1
      description: delete the Biz
      operationId: BizController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.Biz:
    title: Biz
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Name:
        type: string
tags:
- name: v1
  description: |
    BizController operations for Biz
